# Generated by Django 4.2.2 on 2023-06-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_order_delivery_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_crew',
        ),
    ]
